In [1]:
# importing OpenCV(cv2) module
import cv2
import numpy as np
from scipy import fftpack,signal
# import matplotlib.pyplot as plt

In [2]:
img = cv2.imread('lion.png') #reading the lion image
img = cv2.resize(img,(512,512)) #resizing the image to 512x512
cv2.imshow('Lion image', img) #displaying the lion image
image = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2GRAY) #storing the grey colour version 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
#defining the kernel 
K = [[0, 0.01, 0.01, 0.01,0], [0.1, 0.05, 0.05, 0.05,0.1], [0.1, 0.05, 0.25, 0.05,0.1], [0.1, 0.05, 0.05, 0.05,0.1] , [0, 0.01, 0.01, 0.01,0]] #kernel

In [4]:
def convolve2D(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [5]:
image_blur = convolve2D(image, K, padding=2) #performing the 2D convolution
cv2.imwrite('BlurredImage.jpg', image_blur) #storing the resultant image
cv2.imshow('Blurred Lion image', cv2.imread('BlurredImage.jpg')) #displaying the Blurred lion image
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 144. ... 221.   0.   0.]
 ...
 [  0.   0.  54. ... 130.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [6]:
#adding noise to the image
row,col= image.shape
mean = 1
var = 3
sigma = var**0.5
gauss = np.random.normal(mean,sigma,(row,col))
gauss = gauss.reshape(row,col)
noisyimage = image + gauss

cv2.imwrite('NoisyImage.jpg', noisyimage) #storing the resultant image
cv2.imshow('Lion image', image)
cv2.imshow('Noisy Lion image', cv2.imread('NoisyImage.jpg')) #displaying the deconvoluted Blurred lion image
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#Wiener Filtering
filt_img = signal.wiener(image_blur,(3,3))
cv2.imwrite('FilteredBlurImage.jpg', filt_img) #storing the resultant image
cv2.imshow('Filtered Blur Lion image', cv2.imread('FilteredBlurImage.jpg')) #displaying the deconvoluted Blurred lion image
cv2.waitKey(0)
cv2.destroyAllWindows()

filt_img = signal.wiener(noisyimage,(5,5))
cv2.imwrite('FilteredNoiseImage.jpg', filt_img) #storing the resultant image
cv2.imshow('Filtered Noisy Lion image', cv2.imread('FilteredNoiseImage.jpg')) #displaying the deconvoluted Blurred lion image
cv2.waitKey(0)
cv2.destroyAllWindows()

d:\Python\Lib\site-packages\scipy\signal\_signaltools.py:1657: RuntimeWarning: divide by zero encountered in divide
  res *= (1 - noise / lVar)
d:\Python\Lib\site-packages\scipy\signal\_signaltools.py:1657: RuntimeWarning: invalid value encountered in multiply
  res *= (1 - noise / lVar)
